# .github/workflows/build.yml
name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Git commit hash and current date
        id: vars
        run: |
          GIT_HASH=$(git rev-parse --short HEAD)
          DATE_TAG=$(date +"%Y-%m-%d-%H%M")
          echo "GIT_HASH=$GIT_HASH" >> $GITHUB_ENV
          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV
          echo "TAG=${GIT_HASH}-${DATE_TAG}" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ env.TAG }}

      - name: Verify Docker Image Build and Push
        run: |
          # Check if the Docker image exists in the local images list
          docker images | grep ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ env.TAG }}
          if [ $? -ne 0 ]; then
            echo "Docker image build or push failed!"
            exit 1
          fi
          echo "Verifying if the Docker image exists on DockerHub..."
          IMAGE_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/hello-world/tags/${{ env.TAG }}")
          if [ "$IMAGE_EXISTS" -ne 200 ]; then
            echo "Docker image was not pushed to DockerHub successfully!"
            exit 1
          fi
