# .github/workflows/deploy.yml 
name: Deploy Docker Image

on:
  #workflow_run:
  #  workflows: ["Build Docker Image"]  # The name of your CI workflow
  #  types:
  #    - completed
  #schedule:
  #  - cron: '45 8 * * *' # convert time ITC to PST
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Use the image tag from CI
        id: get_image_tag
        run: |
          # The IMAGE_TAG environment variable is set in the CI workflow, so we reference it here
          echo "Using the image tag ${{ env.IMAGE_TAG }}"
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" >> $GITHUB_ENV  # Make sure it's available for later steps

      - name: Pull the Docker image
        run: |
          echo "Pulling the Docker image with tag ${{ env.IMAGE_TAG }}"
          docker pull ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ env.IMAGE_TAG }}

      - name: Stop & Remove Existing Containers
        id: stop_remove_containers
        run: |
          docker stop hello-world || true
          docker rm hello-world || true

      - name: Run Docker Container
        run: |
          docker run -d -p 80:3000 --name hello-world ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ env.IMAGE_TAG }}
          docker ps -a | grep hello-world
