name: Build & Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get Git commit hash and current date
      id: vars
      run: |
         GIT_HASH=$(git rev-parse --short HEAD)
         DATE_TAG=$(date +"%Y-%m-%d-%H%M")
         echo "GIT_HASH=$GIT_HASH" >> $GITHUB_ENV
         echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV
         echo "TAG=${GIT_HASH}-${DATE_TAG}" >> $GITHUB_ENV


    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hello-world:$GITHUB_ENV
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up docker buildx      
      uses: docker/setup-buildx-action@v2
    - name: Log in to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/hello-world:$GITHUB_ENV
    - name: Stop & Remove Existing Containers
      run: docker run -d -p 80:3000 --name hello-world ${{ secrets.DOCKER_USERNAME }}/hello-world:$GITHUB_ENV
    - name: Verify Docker Container is Running
      run: docker ps -a   

           
